### ISSUE TITLE
Cannot install experimental libdap .deb package from Hyrax 1.11 release (Ubuntu 14.04)

### ISSUE THREAD

**Issue by michaeljb** [OPENDAP/libdap4#2]
I downloaded `libdap_3.14.0-1_x86_64.deb` from [OPeNDAP's experimental debian package index][0], but ran into a dependency issue when trying to install it with `gdebi`. Apparently it requires the package `libcurl`, which is not available in the default repos for Ubuntu 14.04 (Trusty Tahr).

There is, however, a package named [`libcurl3`][1] available for Trusty Tahr; maybe the dependency could be changed to this in the published .deb?

Below is my output showing the failed installation:

```
~$ sudo gdebi libdap_3.14.0-1_x86_64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Building data structures... Done
Building data structures... Done
This package is uninstallable
Dependency is not satisfiable: libcurl

```

The development package, `libdap-devel_3.14.0-1_x86_64.deb`, installed without issue.

[0]: http://www.opendap.org/pub/binary/hyrax-1.11/ubuntu14/
[1]: http://packages.ubuntu.com/trusty/libcurl3

**Comment by michaeljb** [comment]
See also https://github.com/OPENDAP/bes/issues/2

**Comment by michaeljb** [comment]
System Info: 

System info:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty
~$ uname -a
Linux vtelemark 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jgallagher59701** [comment]
I'm closing this - this was an experiment to see if we could build deb packages from our RPMs. I think libdap and BES are too complex for this and we should seek a different solution like finding someone who can configure a native build for us. We might be able to integrate that into our Travis CI configuration.
