### ISSUE TITLE
support portablexdr

### ISSUE THREAD

**Issue by jeroen** [OPENDAP/libdap4#33]
Trying to build `libdap` on windows with `mingw-w64` but I can't get the configure script to pick up on portablexdr (which is the only xdr that I can find for windows).

Example headers [here](http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-portablexdr-4.9.2.r27.94fb83c-1-any.pkg.tar.xz).

**Comment by ndp-opendap** [comment]
Hi Jeroen,

At this time we do not support MS-Windows (any version) so I am afraid you are pretty much on your own in working out how to make this compile. James might have some additional insight, but he will be out of the office until mid August. If your effort to compile libdap is the first step in an attempt to compile and run the Hyrax server on Windows we have a project, "hyrax-docker", that is nearly ready for release which might be of use.

Sincerely, 

Nathan

**Comment by jeroen** [comment]
We're trying to support `dap` in the `netcdf` bindings for R.

**Comment by ndp-opendap** [comment]
That's a laudable undertaking, but I am afraid that you will need to work with James on modifying the production rules for libdap to utilize this alternate XDR lib. My autoconf/automake skills are not nearly as good as his in this regard. We can see what he says when he get's back. Thanks for your patience.

Sincerely,
Nathan

**Comment by jeroen** [comment]
OK I will be patient. Can you perhaps help me summarize in one or two sentences what xdr is used/needed for? Is it something we could do without?

**Comment by ndp-opendap** [comment]
In libdap the XDR lib is used for (de)serialization of data on the wire. I believe that it is a required dependency. I sorry I can't be more help at the moment. I will be off line starting immediately for a few days - leaving to catch plane and travel etc. I'll check back when I get into the office this week.

Thanks,
N

**Comment by mjwoods** [comment]
Hi @ndp-opendap, it turns out that @jeroen did not need libdap to build netcdf with opendap support on Windows. The current netcdf source package (v4.4.1.1) includes its own opendap code (possibly derived from libdap), and it is built automatically if libcurl is detected by the configure script. The resulting netcdf library is able to read data from opendap servers, at least on 64-bit Windows. We have a crash problem on 32-bit Windows which needs further investigation.

**Comment by mdsumner** [comment]
Great,  this is good to know.

**Comment by jgallagher59701** [comment]
I'm going to close this - a portable XDR library would be a good addition to libdap, however. I tried the link above in the first message but could not get access to the headers. I'll look around and see about adding something to the library.
