### ISSUE TITLE
unit-tests/HTTPCacheTest expects filesystem with 4KB blocks

### ISSUE THREAD

**Issue by sharkcz** [OPENDAP/libdap4#35]
I've tried to run the full test-suite on a Fedora ppc64le system with XFS system and got failure in HTTPCacheTest 

```
.....................F.


!!!FAILURES!!!
Test Results:
Run:  22   Failures: 1   Errors: 0


1) test: libdap::HTTPCacheTest::cache_gc_test (F) line: 812 HTTPCacheTest.cc
assertion failed
- Expression: pc->d_http_cache_table->d_block_size == 4096


FAIL HTTPCacheTest (exit status: 1)
```
When I checked the `pc->d_http_cache_table->d_block_size` value I got 64K, then I looked for other differences and the only one was the filesystem, there is no problem with ppc systems with ext4, but this particular one has XFS.

**Comment by sharkcz** [comment]
https://github.com/OPENDAP/libdap4/blob/master/HTTPCache.cc#L277 is where the block size is set

**Comment by jgallagher59701** [comment]
It seems odd, to test the blocksize at all. It is what it is. I see it is tested against the d_current_size field in the ctor_test up above on line 205[0]. I'd suggest removing the test on line 812[1]. Does that fix the problem?

[0]: https://github.com/OPENDAP/libdap4/blob/master/unit-tests/HTTPCacheTest.cc#L205
[1]: https://github.com/OPENDAP/libdap4/blob/master/unit-tests/HTTPCacheTest.cc#L812

**Comment by sharkcz** [comment]
yes, after removing the assert from line 812 the test passes

**Comment by jgallagher59701** [comment]
I removed that part of the test.
